### ISSUE TITLE
Axios 0.21.4 flagged for vulnerability IN1-JS-AXIOS-6144788

### ISSUE THREAD

**Issue by perryahn** [tflanagan/node-e-trade#10]
Hello, the current axios version suffers "high" vulnerability IN1-JS-AXIOS-6144788 (flagged by AWS inspector), details [here](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788).

Can we upgrade axios to the latest version? The vulnerability is resolved in 1.6.4 and beyond.

**Comment by tflanagan** [comment]
I pushed `v0.3.0` that updates dependencies. Thanks for the report, apologies for the delay in resolving these.
