### ISSUE TITLE
Portfolios that are empty returns error instead of empty

### ISSUE THREAD

**Issue by buildgreatthings** [tflanagan/node-e-trade#3]
The E*Trade API returns `""` when there is an empty portfolio. A quick fix for this would be to change the return statement to return an empty {} when the API returns. 

https://github.com/tflanagan/node-e-trade/blob/master/src/e-trade-api.ts#L653

I run an async function that calls this command, so the fact that the error isn't propagating up is challenging to work with.

**Comment by tflanagan** [comment]
@awcchungster Is an empty response an error? I'm a bit thrown by your third sentence.

I can easily add a `|| {}` to the return statement if that works for you.

**Comment by buildgreatthings** [comment]
Correct, the library return an error.

**Comment by tflanagan** [comment]
Ah, ok, would something like this resolve it? I don't have a functional test case in front of me that reproduces this issue

```ts
const response = await this.request<any>(requestOptions);

return response?.PortfolioResponse?.AccountPortfolio || {};
```
